import { ReactNode } from "react";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "flowbite/dist/flowbite.css";
import Footer from "@/components/Footer";
// import Navbar from "@/components/Navbar";
import TheBar from "@/components/TheBar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "CleanCuan",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TheBar>
          <div className="min-h-screen flex flex-col">
            <main className=" flex-1 p-0 m-0">{children}</main>
          </div>
            <Footer />
        </TheBar>
      </body>
    </html>
  );
}
